# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Treat these as warnings for better code quality
    unused_local_variable: warning
    unused_element: warning
    dead_code: warning
    use_decorated_box: ignore
    deprecated_member_use: ignore
    avoid_redundant_argument_values: ignore
    use_build_context_synchronously: ignore
    avoid_print: ignore
    unnecessary_brace_in_string_interps: ignore
    curly_braces_in_flow_control_structures: ignore
    empty_catches: ignore
    library_private_types_in_public_api: ignore
    unawaited_futures: ignore
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    prefer_final_fields: ignore
    prefer_conditional_assignment: ignore
    deprecated_member_use_from_same_package: ignore
    unnecessary_import: ignore
    use_colored_box: ignore
    constant_identifier_names: ignore

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at https://dart.dev/lints.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    # Performance-focused lint rules
    avoid_print: true  # Avoid print statements in production
    prefer_const_constructors: true  # Use const where possible for performance
    prefer_const_declarations: true  # Prefer const for immutable values
    prefer_const_literals_to_create_immutables: true  # Use const for immutable collections
    prefer_final_locals: true  # Use final for non-reassigned variables
    prefer_final_in_for_each: true  # Use final in for-each loops
    use_build_context_synchronously: true  # Prevent async context issues
    avoid_unnecessary_containers: true  # Reduce widget tree depth
    sized_box_for_whitespace: true  # Use SizedBox instead of Container for spacing
    sized_box_shrink_expand: true  # Use SizedBox.shrink() and .expand()
    use_key_in_widget_constructors: true  # Use keys for efficient widget rebuilds
    prefer_single_quotes: true  # Consistent quote style
    sort_child_properties_last: true  # Keep child property last for readability
    use_colored_box: true  # Use ColoredBox instead of Container with just color
    use_decorated_box: true  # Use DecoratedBox instead of Container with just decoration
    avoid_redundant_argument_values: true  # Avoid redundant default values
    unnecessary_await_in_return: true  # Remove unnecessary await
    unawaited_futures: true  # Ensure futures are properly awaited
    cancel_subscriptions: true  # Ensure stream subscriptions are cancelled
    close_sinks: true  # Ensure sinks/controllers are closed
    prefer_spread_collections: true  # Use spread operator for collections

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
